#!/bin/sh

# ENV
exec > /root/misc-setup.log 2>&1

msg() {
    local DATE=$(date '+%d %B %Y %T')
    echo "[ INFO MISC ] $1"
}


# Step 1: Remove sysinfo banner if Devices Amlogic
# Step 1: Remove sysinfo banner if Devices Amlogic
msg "Step 1: Remove sysinfo banner if Devices Amlogic"
if opkg list-installed | grep -q "^luci-app-amlogic "; then
    rm -rf /etc/profile.d/30-sysinfo.sh
fi


# Step 2: Remove login password required when accessing terminal
msg "Step 2: Remove login password required when accessing terminal"
uci set ttyd.@ttyd[0].command='/bin/bash --login'
uci commit ttyd


# Step 3: Remove huawei me909s usb-modeswitch
msg "Step 3: Remove huawei me909s usb-modeswitch"
sed -i -e '/12d1:15c1/,+5d' /etc/usb-mode.json


# Step 4: Remove dw5821e usb-modeswitch
msg "Step 4: Remove dw5821e usb-modeswitch"
sed -i -e '/413c:81d7/,+5d' /etc/usb-mode.json


# Step 5: Disable /etc/config/xmm-modem
msg "Step 5: Disable /etc/config/xmm-modem"
uci set xmm-modem.@xmm-modem[0].enable='0'
uci commit xmm-modem


# Step 7: Setup Auto Vnstat Database Backup
msg "Step 7: Setup Auto Vnstat Database Backup"
sed -i 's/;DatabaseDir "\/var\/lib\/vnstat"/DatabaseDir "\/etc\/vnstat"/' /etc/vnstat.conf
mkdir -p /etc/vnstat
chmod +x /etc/init.d/vnstat_backup
bash /etc/init.d/vnstat_backup enable


# Step 10: Adding New Line For Enable i2c Oled Display if Devices Supported
msg "Step 10: Adding New Line For Enable i2c Oled Display if Devices Supported"
if grep -q "Raspberry Pi 4\|Raspberry Pi 3" /proc/cpuinfo; then
    echo -e "\ndtparam=i2c1=on\ndtparam=spi=on\ndtparam=i2s=on" >> /boot/config.txt
fi


# Step 12: Setting Tinyfm
msg "Step 12: Setting Tinyfm"
ln -s / /www/tinyfm/rootfs


# Log success
msg "Misc Setup settings successfully applied..."

# Remove this script after successful execution
rm -f /etc/uci-defaults/$(basename $0)
